#!/bin/sh
java -Xmx2G -cp ../brushfire-scalding/target/brushfire-scalding-0.5.0-SNAPSHOT-jar-with-dependencies.jar \
com.twitter.scalding.Tool \
com.stripe.brushfire.scalding.DigitsJob \
--local \
--input digits.data \
--output digits.output
