#!/bin/sh
java -Xmx2G -cp ../target/brushfire-0.4.0-SNAPSHOT-jar-with-dependencies.jar \
com.twitter.scalding.Tool \
com.stripe.brushfire.scalding.IrisJob \
--local \
--input iris.data \
--output iris.output
