#!/bin/sh
java -Xmx2G -cp ../brushfire-scalding/target/scala-2.10/brushfire-scalding-0.7.1-SNAPSHOT-jar-with-dependencies.jar \
com.stripe.brushfire.local.Example \
iris.data \
petal-width petal-length sepal-width sepal-length
