#!/bin/sh
java -Xmx2G -cp ../brushfire-scalding/target/scala-2.11/brushfire-scalding-0.6.4-SNAPSHOT-jar-with-dependencies.jar \
  com.twitter.scalding.Tool \
  com.stripe.brushfire.scalding.CsvTrainerJob \
  --local \
  --input iris.data \
  --features petal-width,petal-length,sepal-width,sepal-length,species \
  --label species \
  --output iris.output
