#!/bin/sh
java -Xmx2G -cp ../brushfire-scalding/target/brushfire-scalding-0.5.0-SNAPSHOT-jar-with-dependencies.jar \
com.twitter.scalding.Tool \
com.stripe.brushfire.scalding.IrisPostJob \
--local \
--input iris.data \
--load iris.output/mem \
--output iris.output
