#!/bin/sh
java -Xmx2G -cp ../brushfire-scalding/target/scala-2.10/brushfire-scalding-0.6.4-SNAPSHOT-jar-with-dependencies.jar \
com.stripe.brushfire.local.Example \
petal-width petal-length sepal-width sepal-length \
< iris.data
